version: "3.8"
services:
  frontend:
    restart: always
    build:
      dockerfile: ../fullstack-exercise-frontend/Dockerfile
      context: .
    container_name: fullstack-exercise-frontend-prod
    env_file:
      - ../fullstack-exercise-frontend/.env
    ports:
      - 3000:3000